ContosoUniversity/Pages/Courses/Delete.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using ContosoUniversity.Data;
using ContosoUniversity.Models;
using FluentValidation;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace ContosoUniversity.Pages.Courses;

public class Delete : PageModel
{
    private readonly IMediator _mediator;

    public Delete(IMediator mediator) => _mediator = mediator;

    [BindProperty]
    public Command Data { get; set; }

    public async Task OnGetAsync(Query query) => Data = await _mediator.Send(query);

    public async Task<IActionResult> OnPostAsync()
    {
        await _mediator.Send(Data);

        return this.RedirectToPageJson(nameof(Index));
    }

    public record Query : IRequest<Command>
    {
        public int? Id { get; init; }
    }

    public class QueryValidator : AbstractValidator<Query>
    {
        public QueryValidator()
        {
            RuleFor(m => m.Id).NotNull();
        }
    }

    public class MappingProfile : Profile
    {
        public MappingProfile() => CreateProjection<Course, Command>();
    }

    public class QueryHandler : IRequestHandler<Query, Command>
    {
        private readonly SchoolContext _db;
        private readonly IConfigurationProvider _configuration;

        public QueryHandler(SchoolContext db, IConfigurationProvider configuration)
        {
            _db = db;
            _configuration = configuration;
        }

        public Task<Command> Handle(Query message, CancellationToken token) =>
            _db.Courses
                .Where(c => c.Id == message.Id)
                .ProjectTo<Command>(_configuration)
                .SingleOrDefaultAsync(token);
    }

    public record Command : IRequest
    {
        [Display(Name = "Number")]
        public int Id { get; init; }
        public string Title { get; init; }
        public int Credits { get; init; }

        [Display(Name = "Department")]
        public string DepartmentName { get; init; }
    }

    public class CommandHandler : IRequestHandler<Command>
    {
        private readonly SchoolContext _db;

        public CommandHandler(SchoolContext db) => _db = db;

        public async Task<Unit> Handle(Command message, CancellationToken token)
        {
            var course = await _db.Courses.FindAsync(message.Id);

            _db.Courses.Remove(course);

            return default;
        }
    }
}

ContosoUniversity/Pages/Courses/Details.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using ContosoUniversity.Data;
using ContosoUniversity.Models;
using FluentValidation;
using MediatR;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace ContosoUniversity.Pages.Courses;

public class Details : PageModel
{
    private readonly IMediator _mediator;

    public Details(IMediator mediator) => _mediator = mediator;

    public Model Data { get; private set; }

    public async Task OnGetAsync(Query query) => Data = await _mediator.Send(query);

    public record Query : IRequest<Model>
    {
        public int? Id { get; init; }
    }

    public class Validator : AbstractValidator<Query>
    {
        public Validator()
        {
            RuleFor(m => m.Id).NotNull();
        }
    }

    public record Model
    {
        public int Id { get; init; }
        public string Title { get; init; }
        public int Credits { get; init; }
        [Display(Name = "Department")]
        public string DepartmentName { get; init; }
    }

    public class MappingProfile : Profile
    {
        public MappingProfile() => CreateProjection<Course, Model>();
    }

    public class QueryHandler : IRequestHandler<Query, Model>
    {
        private readonly SchoolContext _db;
        private readonly IConfigurationProvider _configuration;

        public QueryHandler(SchoolContext db, IConfigurationProvider configuration)
        {
            _db = db;
            _configuration = configuration;
        }

        public Task<Model> Handle(Query message, CancellationToken token) => 
            _db.Courses
                .Where(i => i.Id == message.Id)
                .ProjectTo<Model>(_configuration)
                .SingleOrDefaultAsync(token);
    }
}

ContosoUniversity/Pages/Departments/Delete.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using ContosoUniversity.Data;
using ContosoUniversity.Models;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace ContosoUniversity.Pages.Departments;

public class Delete : PageModel
{
    private readonly IMediator _mediator;

    public Delete(IMediator mediator) => _mediator = mediator;

    [BindProperty]
    public Command Data { get; set; }

    public async Task OnGetAsync(Query query)
        => Data = await _mediator.Send(query);

    public async Task<ActionResult> OnPostAsync()
    {
        await _mediator.Send(Data);

        return this.RedirectToPageJson("Index");
    }

    public record Query : IRequest<Command>
    {
        public int Id { get; init; }
    }

    public record Command : IRequest
    {
        public string Name { get; init; }

        public decimal Budget { get; init; }

        public DateTime StartDate { get; init; }

        public int Id { get; init; }

        [Display(Name = "Administrator")]
        public string AdministratorFullName { get; init; }

        public byte[] RowVersion { get; init; }
    }

    public class MappingProfile : Profile
    {
        public MappingProfile() => CreateProjection<Department, Command>();
    }

    public class QueryHandler : IRequestHandler<Query, Command>
    {
        private readonly SchoolContext _db;
        private readonly IConfigurationProvider _configuration;

        public QueryHandler(SchoolContext db, IConfigurationProvider configuration)
        {
            _db = db;
            _configuration = configuration;
        }

        public async Task<Command> Handle(Query message, CancellationToken token) => await _db
            .Departments
            .Where(d => d.Id == message.Id)
            .ProjectTo<Command>(_configuration)
            .SingleOrDefaultAsync(token);
    }

    public class CommandHandler : IRequestHandler<Command>
    {
        private readonly SchoolContext _db;

        public CommandHandler(SchoolContext db) => _db = db;

        public async Task<Unit> Handle(Command message, CancellationToken token)
        {
            var department = await _db.Departments.FindAsync(message.Id);

            _db.Departments.Remove(department);

            return default;
        }
    }
}

ContosoUniversity/Pages/Departments/Details.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using ContosoUniversity.Data;
using ContosoUniversity.Models;
using DelegateDecompiler.EntityFrameworkCore;
using MediatR;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace ContosoUniversity.Pages.Departments;

public class Details : PageModel
{
    private readonly IMediator _mediator;

    public Model Data { get; private set; }

    public Details(IMediator mediator) => _mediator = mediator;

    public async Task OnGetAsync(Query query)
        => Data = await _mediator.Send(query);

    public record Query : IRequest<Model>
    {
        public int Id { get; init; }
    }

    public record Model
    {
        public string Name { get; init; }

        public decimal Budget { get; init; }

        public DateTime StartDate { get; init; }

        public int Id { get; init; }

        [Display(Name = "Administrator")]
        public string AdministratorFullName { get; init; }
    }

    public class MappingProfile : Profile
    {
        public MappingProfile() => CreateProjection<Department, Model>();
    }
        
    public class QueryHandler : IRequestHandler<Query, Model>
    {
        private readonly SchoolContext _db;
        private readonly IConfigurationProvider _configuration;

        public QueryHandler(SchoolContext db, IConfigurationProvider configuration)
        {
            _db = db;
            _configuration = configuration;
        }

        public Task<Model> Handle(Query message, 
            CancellationToken token) => 
            _db.Departments
                .Where(m => m.Id == message.Id)
                .ProjectTo<Model>(_configuration)
                .DecompileAsync()
                .SingleOrDefaultAsync(token);
    }
}

ContosoUniversity/Pages/Instructors/CreateEdit.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using ContosoUniversity.Data;
using ContosoUniversity.Models;
using FluentValidation;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace ContosoUniversity.Pages.Instructors;

public class CreateEdit : PageModel
{
    private readonly IMediator _mediator;

    [BindProperty]
    public Command Data { get; set; }

    public CreateEdit(IMediator mediator) => _mediator = mediator;

    public async Task OnGetCreateAsync() => Data = await _mediator.Send(new Query());

    public async Task<IActionResult> OnPostCreateAsync()
    {
        await _mediator.Send(Data);

        return this.RedirectToPageJson(nameof(Index));
    }

    public async Task OnGetEditAsync(Query query) => Data = await _mediator.Send(query);

    public async Task<IActionResult> OnPostEditAsync()
    {
        await _mediator.Send(Data);

        return this.RedirectToPageJson(nameof(Index));
    }

    public record Query : IRequest<Command>
    {
        public int? Id { get; init; }
    }

    public class QueryValidator : AbstractValidator<Query>
    {
        public QueryValidator()
        {
            RuleFor(m => m.Id).NotNull();
        }
    }

    public record Command : IRequest<int>
    {
        public Command()
        {
            AssignedCourses = new List<AssignedCourseData>();
            CourseAssignments = new List<CourseAssignment>();
            SelectedCourses = new string[0];
        }

        public int? Id { get; init; }

        public string LastName { get; init; }
        [Display(Name = "First Name")]
        public string FirstMidName { get; init; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime? HireDate { get; init; }

        [Display(Name = "Location")]
        public string OfficeAssignmentLocation { get; init; }

        public string[] SelectedCourses { get; init; }

        public List<AssignedCourseData> AssignedCourses { get; init; }
        public List<CourseAssignment> CourseAssignments { get; init; }

        public record AssignedCourseData
        {
            public int CourseId { get; init; }
            public string Title { get; init; }
            public bool Assigned { get; init; }
        }

        public record CourseAssignment
        {
            public int CourseId { get; init; }
        }
    }

    public class CommandValidator : AbstractValidator<Command>
    {
        public CommandValidator()
        {
            RuleFor(m => m.LastName).NotNull().Length(0, 50);
            RuleFor(m => m.FirstMidName).NotNull().Length(0, 50);
            RuleFor(m => m.HireDate).NotNull();
        }
    }

    public class MappingProfile : Profile
    {
        public MappingProfile()
        {
            CreateProjection<Instructor, Command>()
                .ForMember(d => d.SelectedCourses, opt => opt.Ignore())
                .ForMember(d => d.AssignedCourses, opt => opt.Ignore());
            CreateProjection<CourseAssignment, Command.CourseAssignment>();
        }
    }

    public class QueryHandler : IRequestHandler<Query, Command>
    {
        private readonly SchoolContext _db;
        private readonly IConfigurationProvider _configuration;

        public QueryHandler(SchoolContext db, IConfigurationProvider configuration)
        {
            _db = db;
            _configuration = configuration;
        }

        public async Task<Command> Handle(Query message, CancellationToken token)
        {
            Command model;
            if (message.Id == null)
            {
                model = new Command();
            }
            else
            {
                model = await _db.Instructors
                    .Where(i => i.Id == message.Id)
                    .ProjectTo<Command>(_configuration)
                    .SingleOrDefaultAsync(token);
            }

            var instructorCourses = new HashSet<int>(model.CourseAssignments.Select(c => c.CourseId));
            var viewModel = _db.Courses.Select(course => new Command.AssignedCourseData
            {
                CourseId = course.Id,
                Title = course.Title,
                Assigned = instructorCourses.Any() && instructorCourses.Contains(course.Id)
            }).ToList();

            model = model with { AssignedCourses = viewModel };

            return model;
        }
    }

    public class CommandHandler : IRequestHandler<Command, int>
    {
        private readonly SchoolContext _db;

        public CommandHandler(SchoolContext db) => _db = db;

        public async Task<int> Handle(Command message, CancellationToken token)
        {
            Instructor instructor;
            if (message.Id == null)
            {
                instructor = new Instructor();
                await _db.Instructors.AddAsync(instructor, token);
            }
            else
            {
                instructor = await _db.Instructors
                    .Include(i => i.OfficeAssignment)
                    .Include(i => i.CourseAssignments)
                    .Where(i => i.Id == message.Id)
                    .SingleAsync(token);
            }

            var courses = await _db.Courses.ToListAsync(token);

            instructor.Handle(message, courses);

            await _db.SaveChangesAsync(token);

            return instructor.Id;
        }
    }
}

ContosoUniversity/Pages/Instructors/Details.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using ContosoUniversity.Data;
using ContosoUniversity.Models;
using FluentValidation;
using MediatR;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace ContosoUniversity.Pages.Instructors;

public class Details : PageModel
{
    private readonly IMediator _mediator;

    public Details(IMediator mediator) => _mediator = mediator;

    public Model Data { get; private set; }

    public async Task OnGetAsync(Query query) => Data = await _mediator.Send(query);

    public record Query : IRequest<Model>
    {
        public int? Id { get; init; }
    }

    public class Validator : AbstractValidator<Query>
    {
        public Validator()
        {
            RuleFor(m => m.Id).NotNull();
        }
    }

    public record Model
    {
        public int? Id { get; init; }

        public string LastName { get; init; }
        [Display(Name = "First Name")]
        public string FirstMidName { get; init; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime? HireDate { get; init; }

        [Display(Name = "Location")]
        public string OfficeAssignmentLocation { get; init; }
    }

    public class MappingProfile : Profile
    {
        public MappingProfile() => CreateProjection<Instructor, Model>();
    }

    public class QueryHandler : IRequestHandler<Query, Model>
    {
        private readonly SchoolContext _db;
        private readonly IConfigurationProvider _configuration;

        public QueryHandler(SchoolContext db, IConfigurationProvider configuration)
        {
            _db = db;
            _configuration = configuration;
        }

        public Task<Model> Handle(Query message, CancellationToken token) => _db
            .Instructors
            .Where(i => i.Id == message.Id)
            .ProjectTo<Model>(_configuration)
            .SingleOrDefaultAsync(token);
    }
}

ContosoUniversity/Pages/Instructors/CreateEdit.cshtml
@page "{handler?}"
@model Instructors.CreateEdit

@{
    ViewBag.Title = Model.Data.Id == null ? "Create" : "Edit";
}

<h2>@(Model.Data.Id == null ? "Create" : "Edit")</h2>

<h4>Instructor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            @Html.ValidationDiv()
            @Html.HiddenFor(m => m.Data.Id)
            @Html.FormBlock(m => m.Data.LastName)
            @Html.FormBlock(m => m.Data.FirstMidName)
            @Html.FormBlock(m => m.Data.HireDate)
            @Html.FormBlock(m => m.Data.OfficeAssignmentLocation)
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <table>
                        <tr>
                        @{
                            int cnt = 0;

                            foreach (var course in Model.Data.AssignedCourses)
                            {
                                if (cnt++ % 3 == 0)
                                {
                                    @:</tr><tr>
                                }
                                @:<td>
                                <label style="font-weight: normal">
                                    <input type="checkbox"
                                           name="data.selectedCourses"
                                           value="@course.CourseId"
                                           @(Html.Raw(course.Assigned ? "checked=\"checked\"" : "")) />
                                    @course.CourseId :  @course.Title
                                </label>
                                @:</td>
                            }
                            @:</tr>
                        }

                    </table>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ContosoUniversity/Pages/Instructors/Delete.cshtml
@page "{id:int}"
@model Instructors.Delete

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Instructor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <display-label-tag for="Data.LastName"/>
        </dt>
        <dd>
            <display-tag for="Data.LastName"/>
        </dd>
        <dt>
            <display-label-tag for="Data.FirstMidName" />
        </dt>
        <dd>
            <display-tag for="Data.FirstMidName" />
        </dd>
        <dt>
            <display-label-tag for="Data.HireDate" />
        </dt>
        <dd>
            <display-tag for="Data.HireDate" />
        </dd>
    </dl>
    
    <form method="post">
        <input-tag for="Data.Id"/>
        <input type="submit" value="Delete" class="btn btn-danger"/> |
        <a asp-page="Index">Back to List</a>
    </form>
</div>

ContosoUniversity/Pages/Instructors/Details.cshtml
@page "{id:int}"
@model Instructors.Details

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Instructor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <display-label-tag for="Data.LastName"/>
        </dt>
        <dd>
            <display-tag for="Data.LastName" />
        </dd>
        <dt>
            <display-label-tag for="Data.FirstMidName" />
        </dt>
        <dd>
            <display-tag for="Data.FirstMidName" />
        </dd>
        <dt>
            <display-label-tag for="Data.HireDate" />
        </dt>
        <dd>
            <display-tag for="Data.HireDate" />
        </dd>
    </dl>
</div>
<div>
    <a asp-page="CreateEdit" asp-page-handler="Edit" asp-route-id="@Model.Data.Id">Edit</a> |
    <a asp-page="Index">Back to List</a>
</div>

ContosoUniversity/Pages/Instructors/Index.cshtml
@page
@model Instructors.Index

@{
    ViewData["Title"] = "Instructors";
}

<h2>Instructors</h2>

<p>
    <a asp-page="CreateEdit" asp-page-handler="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>Last Name</th>
            <th>First Name</th>
            <th>Hire Date</th>
            <th>Office</th>
            <th>Courses</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{ int i = 0; }
        @foreach (var item in Model.Data.Instructors)
        {
            string selectedRow = "";
            if (item.Id == Model.Data.InstructorId)
            {
                selectedRow = "table-success";
            }
            <tr class="@selectedRow">
                <td>
                    <display-tag for="Data.Instructors[i].LastName" />
                </td>
                <td>
                    <display-tag for="Data.Instructors[i].FirstMidName" />
                </td>
                <td>
                    <display-tag for="Data.Instructors[i].HireDate" />
                </td>
                <td>
                    <display-tag for="Data.Instructors[i].OfficeAssignmentLocation" />
                </td>
                <td>
                    @{
                        foreach (var course in item.CourseAssignments)
                        {
                            @course.CourseId @:  @course.CourseTitle <br />
                        }
                    }
                </td>
                <td>
                    <a asp-page="Index" asp-route-id="@item.Id">Select</a> |
                    <a asp-page="CreateEdit" asp-page-handler="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-page="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-page="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
            i++;
        }
    </tbody>
</table>

@if (Model.Data.Courses.Any())
{
    <h3>Courses Taught by Selected Instructor</h3>
    <table class="table">
        <tr>
            <th></th>
            <th>Number</th>
            <th>Title</th>
            <th>Department</th>
        </tr>

        @foreach (var item in Model.Data.Courses)
        {
            string selectedRow = "";
            if (item.Id == Model.Data.CourseId)
            {
                selectedRow = "table-success";
            }
            <tr class="@selectedRow">
                <td>
                    <a asp-page="Index" asp-route-id="@Model.Data.InstructorId" asp-route-courseID="@item.Id">Select</a>
                </td>
                <td>
                    @item.Id
                </td>
                <td>
                    @item.Title
                </td>
                <td>
                    @item.DepartmentName
                </td>
            </tr>
        }

    </table>
}
@if (Model.Data.Enrollments.Any())
{
    <h3>
        Students Enrolled in Selected Course
    </h3>
    <table class="table">
        <tr>
            <th>Name</th>
            <th>Grade</th>
        </tr>
        @{ i = 0; }
        @foreach (var item in Model.Data.Enrollments)
        {
            <tr>
                <td>
                    @item.StudentFullName
                </td>
                <td>
                    <display-tag for="Data.Enrollments[i].Grade" />
                </td>
            </tr>
            i++;
        }
    </table>
            }